import { io, type Socket } from 'socket.io-client';
import { validateNickname } from '../shared/profanity.ts';
import type { ArenaSnapshot, PlayerColor } from '../shared/types.ts';
import './style.css';

const app = document.querySelector<HTMLDivElement>('#app')!;
const colors: PlayerColor[] = ['pink', 'cyan', 'lime', 'orange', 'violet', 'yellow'];
const colorValues: Record<PlayerColor, string> = { pink: '#ff4fa3', cyan: '#4de8e8', lime: '#b8f34a', orange: '#ff914d', violet: '#ad7aff', yellow: '#ffd85c' };
const state = { socket: null as Socket | null, snapshot: null as ArenaSnapshot | null, playerId: '', token: '', connected: false, input: { up: false, down: false, left: false, right: false, firing: false, angle: 0 } };

app.innerHTML = `<main class="shell"><section id="lobby" class="panel lobby"><div class="eyebrow">DOT TANK ARENA <span class="live-dot"></span> LIVE</div><h1>Own the<br><span>dot zone.</span></h1><p class="lede">A chaotic top-down tank arena. Collect XP, level up, and outplay everyone in your lobby.</p><div class="form-row"><label>CALLSIGN<input id="name" maxlength="16" placeholder="Pick a nickname" autocomplete="off"></label><label>COLOR<div id="colors" class="color-picker"></div></label></div><button id="play" class="primary">QUEUE FOR ARENA <span>&rarr;</span></button><p id="error" class="error"></p><div class="rules"><div><strong>WASD</strong><span>move</span></div><div><strong>MOUSE</strong><span>aim + fire</span></div><div><strong>DOTS</strong><span>give XP</span></div></div></section><section id="game" class="game hidden"><canvas id="arena"></canvas><div class="hud"><div class="brand">DOT TANK <span>&bull; LIVE</span></div><div id="status" class="status">CONNECTING</div><div id="leaderboard" class="leaderboard"></div></div><div class="mobile-controls"><div id="stick" class="stick"><i></i></div><button id="fire" class="fire">FIRE</button></div><div id="toast" class="toast"></div></section></main>`;

const colorPicker = document.querySelector<HTMLDivElement>('#colors')!; let selectedColor: PlayerColor = 'pink';
colorPicker.innerHTML = colors.map((color) => `<button class="swatch ${color}" data-color="${color}" aria-label="${color}"></button>`).join('');
colorPicker.querySelector(`[data-color="${selectedColor}"]`)?.classList.add('selected');
colorPicker.addEventListener('click', (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('[data-color]'); if (!button) return; selectedColor = button.dataset.color as PlayerColor; colorPicker.querySelectorAll('.swatch').forEach((swatch) => swatch.classList.toggle('selected', swatch === button)); });

const errorElement = document.querySelector<HTMLParagraphElement>('#error')!;
document.querySelector('#play')!.addEventListener('click', () => { const result = validateNickname(document.querySelector<HTMLInputElement>('#name')!.value); if (!result.ok) { errorElement.textContent = result.error; return; } errorElement.textContent = ''; connect(result.value); });
function connect(name: string) { const serverUrl = import.meta.env.VITE_SERVER_URL || (window.location.hostname === 'localhost' ? 'http://localhost:3001' : window.location.origin); state.socket?.disconnect(); state.socket = io(serverUrl, { transports: ['websocket', 'polling'], reconnection: true }); state.socket.on('connect', () => { state.connected = true; if (state.token) state.socket!.emit('player:reconnect', { token: state.token }); else state.socket!.emit('queue:join', { name, color: selectedColor }); }); state.socket.on('connect_error', () => { errorElement.textContent = 'Unable to reach the arena server.'; }); state.socket.on('session:ready', (data) => { state.token = data.token; state.playerId = data.playerId; document.querySelector('#lobby')!.classList.add('hidden'); document.querySelector('#game')!.classList.remove('hidden'); }); state.socket.on('arena:state', (snapshot: ArenaSnapshot) => { state.snapshot = snapshot; renderHud(); }); state.socket.on('player:error', (data) => { errorElement.textContent = data.message; }); state.socket.on('disconnect', () => { state.connected = false; showToast('CONNECTION LOST - RECONNECTING'); }); }
function renderHud() { if (!state.snapshot) return; const player = state.snapshot.players.find((candidate) => candidate.id === state.playerId); document.querySelector('#status')!.textContent = player ? `ARENA ${String(state.snapshot.arenaId + 1).padStart(2, '0')} · ${state.snapshot.online}/10 PLAYERS` : 'QUEUING'; const rows = [...state.snapshot.players].sort((a, b) => b.xp - a.xp).slice(0, 8).map((candidate, index) => `<div class="rank"><b>${String(index + 1).padStart(2, '0')}</b><i class="mini ${candidate.color}"></i><span>${escapeHtml(candidate.name)}<small>${candidate.xp} XP · ${candidate.eliminations}K/${candidate.deaths}D</small></span><em>LVL ${candidate.level}</em></div>`).join(''); document.querySelector('#leaderboard')!.innerHTML = `<h3>LEADERBOARD</h3>${rows}`; }
function escapeHtml(value: string) { const entities: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }; return value.replace(/[&<>"']/g, (character) => entities[character]); }
function showToast(message: string) { const toast = document.querySelector('#toast')!; toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2500); }

const canvas = document.querySelector<HTMLCanvasElement>('#arena')!; const context = canvas.getContext('2d')!;
function resize() { const ratio = window.devicePixelRatio || 1; canvas.width = window.innerWidth * ratio; canvas.height = window.innerHeight * ratio; canvas.style.width = `${window.innerWidth}px`; canvas.style.height = `${window.innerHeight}px`; context.setTransform(ratio, 0, 0, ratio, 0, 0); } window.addEventListener('resize', resize); resize();
function draw() { const width = window.innerWidth; const height = window.innerHeight; context.clearRect(0, 0, width, height); context.fillStyle = '#080b15'; context.fillRect(0, 0, width, height); if (state.snapshot) { const me = state.snapshot.players.find((player) => player.id === state.playerId) ?? state.snapshot.players[0]; const scale = Math.min(width / 920, height / 650); const ox = width / 2 - (me?.x ?? 1100) * scale; const oy = height / 2 - (me?.y ?? 700) * scale; context.save(); context.translate(ox, oy); context.scale(scale, scale); context.strokeStyle = '#222943'; context.lineWidth = 5; context.strokeRect(0, 0, 2200, 1400); for (const dot of state.snapshot.dots) { context.fillStyle = '#ffd85c'; context.beginPath(); context.arc(dot.x, dot.y, 7, 0, Math.PI * 2); context.fill(); } for (const player of state.snapshot.players) { const playerColor = colorValues[player.color]; context.save(); context.translate(player.x, player.y); context.rotate(player.angle); context.fillStyle = player.shielded ? '#fff' : '#101426'; context.strokeStyle = playerColor; context.lineWidth = 5; context.fillRect(-22, -17, 44, 34); context.strokeRect(-22, -17, 44, 34); context.fillStyle = playerColor; context.fillRect(0, -6, 31, 12); context.restore(); context.fillStyle = '#f6f1e8'; context.font = 'bold 12px monospace'; context.textAlign = 'center'; context.fillText(`${player.name}  LVL ${player.level}`, player.x, player.y - 32); context.fillStyle = '#311d2b'; context.fillRect(player.x - 28, player.y - 25, 56, 5); context.fillStyle = playerColor; context.fillRect(player.x - 28, player.y - 25, 56 * (player.health / player.maxHealth), 5); } context.restore(); } requestAnimationFrame(draw); } draw();

window.addEventListener('keydown', (event) => { const key = event.key.toLowerCase(); if (key === 'w' || key === 'arrowup') state.input.up = true; if (key === 's' || key === 'arrowdown') state.input.down = true; if (key === 'a' || key === 'arrowleft') state.input.left = true; if (key === 'd' || key === 'arrowright') state.input.right = true; }); window.addEventListener('keyup', (event) => { const key = event.key.toLowerCase(); if (key === 'w' || key === 'arrowup') state.input.up = false; if (key === 's' || key === 'arrowdown') state.input.down = false; if (key === 'a' || key === 'arrowleft') state.input.left = false; if (key === 'd' || key === 'arrowright') state.input.right = false; }); window.addEventListener('mousemove', (event) => { state.input.angle = Math.atan2(event.clientY - window.innerHeight / 2, event.clientX - window.innerWidth / 2); }); window.addEventListener('mousedown', () => { state.input.firing = true; }); window.addEventListener('mouseup', () => { state.input.firing = false; });
const stick = document.querySelector<HTMLDivElement>('#stick'); const fire = document.querySelector<HTMLButtonElement>('#fire'); stick?.addEventListener('touchmove', (event) => { const touch = event.touches[0]; const rect = stick.getBoundingClientRect(); const dx = touch.clientX - (rect.left + rect.width / 2); const dy = touch.clientY - (rect.top + rect.height / 2); state.input.left = dx < -12; state.input.right = dx > 12; state.input.up = dy < -12; state.input.down = dy > 12; state.input.angle = Math.atan2(dy, dx); event.preventDefault(); }, { passive: false }); stick?.addEventListener('touchend', () => { state.input.up = false; state.input.down = false; state.input.left = false; state.input.right = false; }); fire?.addEventListener('touchstart', () => { state.input.firing = true; }, { passive: true }); fire?.addEventListener('touchend', () => { state.input.firing = false; }); window.setInterval(() => { if (state.connected) state.socket?.emit('player:input', state.input); }, 50);
